name: shopping_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  passwordfield: ^0.0.5
  shadow: ^0.1.5
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.11.1+6
  google_sign_in: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  fonts:
  - family: IndieFlower
    fonts:
      - asset: assets/fonts/IndieFlower-Regular.ttf
  - family: Manslava
    fonts:
      - asset: assets/fonts/Mansalva-Regular.ttf
  - family: Henny
    fonts:
      - asset: assets/fonts/HennyPenny-Regular.ttf
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/data/categories.json

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true