name: shopping_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  passwordfield: ^0.0.5
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.2+1
  provider: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  fonts:
  - family: IndieFlower
    fonts:
      - asset: assets/fonts/IndieFlower-Regular.ttf
  - family: Manslava
    fonts:
      - asset: assets/fonts/Mansalva-Regular.ttf
  - family: Henny
    fonts:
      - asset: assets/fonts/HennyPenny-Regular.ttf
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/data/categories.json

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true